### ISSUE TITLE
Support decompressing to `stdout`

### ISSUE THREAD

**Issue by marklit** [ouch-org/ouch#110]
Normally passing a dash when decompressing with other tools will cause the decompressor to output to stdout. There doesn't seem to be such support in ouch.

```bash
echo hello > hello.txt
ouch c hello.txt hello.tar.lzma.zst
ouch d hello.tar.lzma.zst - | hexdump -C
```

```
00000000  44 6f 20 79 6f 75 20 77  61 6e 74 20 74 6f 20 6f  |Do you want to o|
00000010  76 65 72 77 72 69 74 65  20 27 2e 2f 68 65 6c 6c  |verwrite './hell|
00000020  6f 2e 74 78 74 27 3f 20  5b 1b 5b 33 38 3b 35 3b  |o.txt'? [.[38;5;|
00000030  31 30 6d 59 1b 5b 33 39  6d 2f 1b 5b 33 38 3b 35  |10mY.[39m/.[38;5|
```

I also tried just compressing a single file as a ZSTD stream instead of tar'ing the file first and ouch crashed. #96 probably covers this issue.

```bash
ouch c hello.txt hello.zst
```

```
thread 'main' panicked at 'internal error: entered unreachab`le code', src/commands.rs:165:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```bash
ouch c hello.txt hello.lzma
```

```
thread 'main' panicked at 'internal error: entered unreachable code', src/commands.rs:165:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by SpyrosRoum** [comment]
I think decompressing to stdout would be a good feature, similar to #6.
About the crash there is a pr open that fixes it.

**Comment by figsoda** [comment]
we should also move all current outputs to stderr, there are still a couple uses of `println` in the code base

**Comment by marcospb19** [comment]
@figsoda great point, everything would need to go to `stderr`, otherwise, decompressing to `stdout` will corrupt all the files.

**Comment by figsoda** [comment]
`ouch d file.xz 2>ouch.log` should work if they are outputted to stderr

**Comment by marcospb19** [comment]
Moving this specific part of the discussion to the dedicated issue #114.
