### ISSUE TITLE
Incorrect partial compression detection leads to crash

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#282]
### Version

385a630d0ecf81344d91266d6552030387bdca0d (main branch)

### Description

When trying to compress a file with extensions `.tar.zst` into `.zip` archive, ouch incorrectly detects that it should do partial compression and crashes.

### Current Behavior

```
$ ouch c less-1:590-1-x86_64.pkg.tar.zst archive.zip 
[INFO] Partial compression detected. Compressing less-1-590.pkg.tar.zst into out.zipPartial compression detected. Compressing less-1-590.pkg.tar.zst into out.zip
thread 'main' panicked at 'removal index (is 0) should be < len (is 0)', src/extension.rs:182:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected Behavior

It should compress the file into a new Zip archive.

**Comment by marcospb19** [comment]
Other example:

```
$ ouch compress less-1-590.pkg.tar.zst out.gz
[INFO] Partial compression detected. Compressing less-1-590.pkg.tar.zst into out.gzPartial compression detected. Compressing less-1-590.pkg.tar.zst into out.gz
thread 'main' panicked at 'removal index (is 0) should be < len (is 0)', src/extension.rs:182:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Approach to this will probably be removing automatic partial compression detection in favor to the `--format` flag, it's less error-prone, more explicit, and more versatile.
